<?php
namespace app\admin\controller;
use think\Controller;
Class Aiskor extends Controller
{
    protected $aiskor = null;
    public function initialize()
    {
        $this->aiskor = model('Aiskor');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        $aiskor = $this->aiskor->select();
        return view('aiskor/index',['aiskor'=>$aiskor]);
    }
    public function add()
    {
        return view('aiskor/add');
    }
    public function save()
    {
        $aiskor = input('post.');
        $isSuccess = $this->aiskor->save($aiskor);
        if($isSuccess){
            return redirect(url('index'));
        }
        return redirect(url('add'));
    }
}