<?php
namespace app\admin\controller;
use think\Controller;
Class Aiskor extends Controller
{
    protected $aiskor = null;
    public function initialize()
    {
        $this->aiskor = model('Aiskor');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        $aiskor = $this->aiskor->select();
        return view('aiskor/index',['aiskor'=>$aiskor]);
    }
    public function add()
    {
        return view('aiskor/add');
    }
    public function save()
    {
        $aiskor = input('post.');
        $isSuccess = $this->aiskor->save($aiskor);
        if($isSuccess){
            return redirect(url('index'));
        }
        return redirect(url('add'));
    }
    //api
    public function aiskorApi()
    {
        try{
            $data = input('');
            if(empty($data['nik']) || empty($data['mobile'])){
                return json(['code'=>101,'info'=>'error,nik or mobile is empty']);
            }
            $aiskor = $this->aiskor->where($data)->select();
        }catch (\Exception $e){
            return json(['code'=>101,'info'=>'error,'.$e->getError()]);
        }
        return json(['code'=>200,'info'=>'success','data'=>$aiskor]);
    }
}