<?php
namespace app\admin\controller;
use think\Controller;
Class Aiskor extends Controller
{
    

    protected $aiskor = null;
    public function initialize()
    {   
        header('Access-Control-Allow-Origin: http://web.aiskor.co.id');
        header("Access-Control-Allow-Credentials: true");
        header("Access-Control-Allow-Methods: GET, POST, PATCH, PUT, OPTIONS");
        header("Access-Control-Allow-Headers: Origin, Content-Type, Cookie, X-CSRF-TOKEN, Accept, Authorization, X-XSRF-TOKEN");
        header("Access-Control-Expose-Headers: *");
        $this->aiskor = model('Aiskor');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        $aiskor = $this->aiskor->select();
        return view('aiskor/index',['aiskor'=>$aiskor]);
    }
    public function add()
    {
        return view('aiskor/add');
    }
    public function save()
    {
        $aiskor = input('post.');
        $this->aiskor->where('1=1')->delete();
        $isSuccess = $this->aiskor->save($aiskor);
        // if($isSuccess){
        //     return redirect(url('index'));
        // }
        return redirect(url('add'));
    }
    //api
    public function aiskorApi()
    {
        
        try{
            $aiskor = $this->aiskor->order('id desc')->find();
        }catch (\Exception $e){
            return json(['code'=>101,'info'=>'error,'.$e->getError()]);
        }
        return json(['code'=>200,'info'=>'success','data'=>$aiskor]);
    }
}